cd ../js/vizualizer/vizualizations/sketches;
touch cat.txt;
echo "">>cat.txt;
echo "//=============================default empty functions" >>cat.txt;
echo -e "p5Viz.customViz=function(p,indx){\nreturn false;}">>cat.txt;
echo -e "p5Viz.customVars=function(p){\nreturn false;}" >>cat.txt;
echo "" >>cat.txt;
echo "//=============================sketches" >>cat.txt;
echo "">>cat.txt;
cat *.js >> cat.txt;
echo "">>cat.txt;
echo "//=============================end of sketches , beginning global connections" >>cat.txt;
echo "" >>cat.txt;
echo "//=============================viz ids" >>cat.txt;
echo "" >>cat.txt;
names=$(sed -E 's|//\"(.*)\"|vizNames.push(\"\1\");\\n|' <<<$(for f in *.js; do read -r line <"$f"; echo  "$line";done));
echo -e $names >>cat.txt;
echo "">>cat.txt;
echo "//=============================Initiating Vizualization" >>cat.txt;
echo "" >>cat.txt;
echo -e "p5Viz.customVars=function(p){\n" >>cat.txt;
i=0;
drawers=();
varInit=();
for f in *.js; do line=$(grep  -E  'p5Viz\.(.*)Vars=function\(p\)'  $f); varInit+=$(sed  -E -e 's|=function\(p\)\{|(p);\\n|g' <<< $line) ;drawers+=$(echo "case $i: \\n $(sed -E -e 's|Vars=function\(p\)\{|(p);\\n|g' <<<$line)\\nbreak;\\n"); let i=$i+1;done;
for inits in $varInit; do echo -e $inits >> cat.txt;  done;
echo "">>cat.txt;
echo "}">>cat.txt;
echo "">>cat.txt;
echo "//=============================framerendering" >>cat.txt;
echo "" >>cat.txt;
echo -e "p5Viz.customViz=function(p,indx){\nswitch(indx){\n">>cat.txt;
for drawer in $drawers; do echo -e $drawers >> cat.txt;  done;
echo "">>cat.txt;
echo "}">>cat.txt;
echo "">>cat.txt;
echo "">>cat.txt;
echo "}">>cat.txt;
echo "">>cat.txt;
echo "">>cat.txt;
echo "//=============================" >>cat.txt;
mv -f cat.txt ../customvizs.js;
cd ../../../../;